# Generated by Django 5.2.8 on 2025-11-23 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Промокод')),
                ('discount_percent', models.DecimalField(decimal_places=0, help_text='Значение скидки в процентах (например, 15)', max_digits=2, verbose_name='Скидка в процентах')),
            ],
        ),
        migrations.AddField(
            model_name='purchase',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.promocode'),
        ),
    ]
